### ISSUE TITLE
Posible cambio en la web de Renfe

### ISSUE THREAD

**Issue by albertotb** [gerardcl/renfe-cli#174]
**Describe the bug**
Parece que Renfe ha retocado ligeramente la web y al intentar obtener los horarios se obtiene el siguiente error:

```
Traceback (most recent call last):
  File "/home/alberto/miniconda3/envs/renfe-cli/bin/renfe-cli", line 8, in <module>
    sys.exit(main())
  File "/home/alberto/miniconda3/envs/renfe-cli/lib/python3.9/site-packages/renfe/cli.py", line 33, in main
    times = get_timetable(
  File "/home/alberto/miniconda3/envs/renfe-cli/lib/python3.9/site-packages/renfe/timetable.py", line 19, in get_timetable
    soup = get_soup(browser, origin, destination, days_from_today, search_timeout)
  File "/home/alberto/miniconda3/envs/renfe-cli/lib/python3.9/site-packages/renfe/timetable.py", line 64, in get_soup
    origin_option = browser.find_element_by_css_selector("#awesomplete_list_1_item_0")
  File "/home/alberto/miniconda3/envs/renfe-cli/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 808, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/alberto/miniconda3/envs/renfe-cli/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/alberto/miniconda3/envs/renfe-cli/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/alberto/miniconda3/envs/renfe-cli/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#awesomplete_list_1_item_0"}
  (Session info: headless chrome=114.0.5735.198)
Stacktrace:
#0 0x5618ce2c64e3 <unknown>
#1 0x5618cdff5c76 <unknown>
#2 0x5618ce031c96 <unknown>
#3 0x5618ce031dc1 <unknown>
#4 0x5618ce06b7f4 <unknown>
#5 0x5618ce05103d <unknown>
#6 0x5618ce06930e <unknown>
#7 0x5618ce050de3 <unknown>
#8 0x5618ce0262dd <unknown>
#9 0x5618ce02734e <unknown>
#10 0x5618ce2863e4 <unknown>
#11 0x5618ce28a3d7 <unknown>
#12 0x5618ce294b20 <unknown>
#13 0x5618ce28b023 <unknown>
#14 0x5618ce2591aa <unknown>
#15 0x5618ce2af6b8 <unknown>
#16 0x5618ce2af847 <unknown>
#17 0x5618ce2bf243 <unknown>
#18 0x7f38bb974b43 <unknown>
```

**To Reproduce**
Ejecutar `renfe-cli -o 17000 -t 31400 -b "chrome"` con Chrome 114 instalado

**Expected behavior**
Que se muestren los horarios

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04

**Comment by gerardcl** [comment]
hola @albertotb ! digo lo mismo que en el otro issue que abriste. Veo que tienes algunos arreglos por lo relativo a que el CLI funcione pero ahora veo que también hay problemas parseando la web ya que hicieron cambios! mas motivación para mi plan de migración del codigo entero hehe a ver cuando le saco tiempo! saludos,
ah! y si tienes un fix, adelante! lo revisaré encantado y en seguida! saludos!

**Comment by gerardcl** [comment]
hola @albertotb , refactor to Rust done, check v4.0.0 if it works for you! :)
closing this issue
please, create new ones for new feature requests or issues!
Best,

**Comment by albertotb** [comment]
It works great now. Thanks!
