### ISSUE TITLE
CLI exits if Firefox is not installed

### ISSUE THREAD

**Issue by mdelapenya** [gerardcl/renfe-cli#83]
**Describe the bug**
The CLI exits execution if Firefox is not installed in the system (Mac in my case)

**To Reproduce**

1. Install CLI on Mac
2. Check firefox is not installed
3. run cli:
```shell
$ renfe-cli -t 92102
```

**Expected behavior**
trains are retrieved

**Current behaviour:** CLI exits with Python stacktrace:
```shell
Today is: 2021-10-19
Searching timetable for date: 2021-10-19
From SILS to TOLEDO
Be patient, navigating through renfe site now...
/bin/sh: /Applications/Firefox.app/Contents/MacOS/firefox: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/renfe-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/renfe/cli.py", line 33, in main
    times = get_timetable(origin_name, destination_name, int(options.days), options.browser, int(options.search_timeout))
  File "/usr/local/lib/python3.9/site-packages/renfe/timetable.py", line 14, in get_timetable
    soup = get_soup(browser, origin, destination, days_from_today, search_timeout)
  File "/usr/local/lib/python3.9/site-packages/renfe/timetable.py", line 42, in get_soup
    browser = get_browser(browser)
  File "/usr/local/lib/python3.9/site-packages/renfe/timetable.py", line 29, in get_browser
    browser = webdriver.Firefox(executable_path=GeckoDriverManager().install(), firefox_options=firefox_options)
  File "/usr/local/lib/python3.9/site-packages/webdriver_manager/firefox.py", line 22, in __init__
    self.driver = GeckoDriver(version=version,
  File "/usr/local/lib/python3.9/site-packages/webdriver_manager/driver.py", line 83, in __init__
    self.browser_version = firefox_version()
  File "/usr/local/lib/python3.9/site-packages/webdriver_manager/utils.py", line 174, in firefox_version
    raise ValueError(f'Could not get version for Firefox with this command: {cmd}')
ValueError: Could not get version for Firefox with this command: /Applications/Firefox.app/Contents/MacOS/firefox --version
```

**Screenshots**
<img width="898" alt="Screenshot 2021-10-19 at 09 59 16" src="https://user-images.githubusercontent.com/951580/137868047-a7cc2e8f-40fd-4359-940c-e6f841fa7ceb.png">

**Environment (please complete the following information):**
 - OS: Mac OS
 - Version:

**Additional context**
I tried passing `-b chrome` to avoid using default browser, but then it fails with another error (a CSS ID that does not exist anymore)

**Comment by mdelapenya** [comment]
Thank you @gerardcl ! 

When I was a regular user of Renfe, I also thought about having a similar CLI, but unfortunately did not have time to implement anything... Now that I'm remote I still want to see the CLI alive to provide useful experience to  advanced users, so feel free to ping me for contributions, beta-testing, etc!!

**Comment by gerardcl** [comment]
a pleasure @mdelapenya ! I had same thoughts but in this case ended up having some time 👍 happy you like it and to want to contribute! feel free to jump and assing the issue to you if you want, I just realised that what you found is indeed a new bug I will try to fix latest this weekend :)    keep in touch!
